"""add ai_insights

Revision ID: 8a1aa7d866d0
Revises: 629afb5668ed
Create Date: 2026-05-29 22:51:09.469084

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  SQLModel 列类型（如 AutoString）在迁移中可能用到

import app.core.money  # noqa: F401  DecimalString 自定义类型

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '8a1aa7d866d0'
down_revision: str | None = '629afb5668ed'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('prompt_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=True),
    sa.Column('completion_tokens', sa.Integer(), nullable=True),
    sa.Column('cost_jpy', app.core.money.DecimalString(), nullable=True),
    sa.Column('response', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_insights_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insights_input_hash'), ['input_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insights_target_id'), ['target_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_insights_target_type'), ['target_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_insights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ai_insights_target_type'))
        batch_op.drop_index(batch_op.f('ix_ai_insights_target_id'))
        batch_op.drop_index(batch_op.f('ix_ai_insights_input_hash'))
        batch_op.drop_index(batch_op.f('ix_ai_insights_created_at'))

    op.drop_table('ai_insights')
    # ### end Alembic commands ###
