"""initial schema

Revision ID: 06c630362431
Revises: 
Create Date: 2026-05-29 21:55:19.261488

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  SQLModel 列类型（如 AutoString）在迁移中可能用到

import app.core.money  # DecimalString 自定义类型

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '06c630362431'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fee_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('broker', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direction', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fee_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate', app.core.money.DecimalString(), nullable=True),
    sa.Column('min_amount', app.core.money.DecimalString(), nullable=True),
    sa.Column('fixed_amount', app.core.money.DecimalString(), nullable=True),
    sa.Column('per_share', app.core.money.DecimalString(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('fee_rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fee_rules_market'), ['market'], unique=False)

    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('industry', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('listed_date', sa.Date(), nullable=True),
    sa.Column('delisted_date', sa.Date(), nullable=True),
    sa.Column('is_etf', sa.Boolean(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'market', name='uq_stock_symbol_market')
    )
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stocks_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_market'), ['market'], unique=False)
        batch_op.create_index(batch_op.f('ix_stocks_symbol'), ['symbol'], unique=False)

    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('action_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ex_date', sa.Date(), nullable=False),
    sa.Column('ratio_num', app.core.money.DecimalString(), nullable=True),
    sa.Column('ratio_den', app.core.money.DecimalString(), nullable=True),
    sa.Column('subscribe_ratio', app.core.money.DecimalString(), nullable=True),
    sa.Column('subscribe_price', app.core.money.DecimalString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_corporate_actions_ex_date'), ['ex_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_corporate_actions_stock_id'), ['stock_id'], unique=False)

    op.create_table('journals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('decision_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('thesis_category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('expected_horizon', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_price', app.core.money.DecimalString(), nullable=True),
    sa.Column('stop_loss_price', app.core.money.DecimalString(), nullable=True),
    sa.Column('exit_condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Integer(), nullable=True),
    sa.Column('emotion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('thesis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('risks', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_journals_stock_id'), ['stock_id'], unique=False)

    op.create_table('prices',
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', app.core.money.DecimalString(), nullable=True),
    sa.Column('high', app.core.money.DecimalString(), nullable=True),
    sa.Column('low', app.core.money.DecimalString(), nullable=True),
    sa.Column('close', app.core.money.DecimalString(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('turnover', app.core.money.DecimalString(), nullable=True),
    sa.Column('adjust_factor', app.core.money.DecimalString(), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('stock_id', 'date')
    )
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_prices_date'), ['date'], unique=False)

    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('journal_id', sa.Integer(), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('days_since_decision', sa.Integer(), nullable=True),
    sa.Column('price_at_review', app.core.money.DecimalString(), nullable=True),
    sa.Column('pnl_pct', app.core.money.DecimalString(), nullable=True),
    sa.Column('benchmark_pnl_pct', app.core.money.DecimalString(), nullable=True),
    sa.Column('thesis_held', sa.Boolean(), nullable=True),
    sa.Column('luck_vs_skill', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lessons', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviews_journal_id'), ['journal_id'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trade_date', sa.Date(), nullable=False),
    sa.Column('quantity', app.core.money.DecimalString(), nullable=False),
    sa.Column('price', app.core.money.DecimalString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fx_rate_to_jpy', app.core.money.DecimalString(), nullable=True),
    sa.Column('commission', app.core.money.DecimalString(), nullable=True),
    sa.Column('tax', app.core.money.DecimalString(), nullable=True),
    sa.Column('other_fees', app.core.money.DecimalString(), nullable=True),
    sa.Column('journal_id', sa.Integer(), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['journal_id'], ['journals.id'], ),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_stock_id'), ['stock_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_trade_date'), ['trade_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_trade_date'))
        batch_op.drop_index(batch_op.f('ix_transactions_stock_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviews_journal_id'))

    op.drop_table('reviews')
    with op.batch_alter_table('prices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_prices_date'))

    op.drop_table('prices')
    with op.batch_alter_table('journals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_journals_stock_id'))

    op.drop_table('journals')
    with op.batch_alter_table('corporate_actions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_corporate_actions_stock_id'))
        batch_op.drop_index(batch_op.f('ix_corporate_actions_ex_date'))

    op.drop_table('corporate_actions')
    with op.batch_alter_table('stocks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stocks_symbol'))
        batch_op.drop_index(batch_op.f('ix_stocks_market'))
        batch_op.drop_index(batch_op.f('ix_stocks_industry'))

    op.drop_table('stocks')
    with op.batch_alter_table('fee_rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fee_rules_market'))

    op.drop_table('fee_rules')
    # ### end Alembic commands ###
