"""add fx_rates

Revision ID: 512bb4dc00a3
Revises: 144bdd18bc83
Create Date: 2026-05-29 22:26:34.006448

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  SQLModel 列类型（如 AutoString）在迁移中可能用到

import app.core.money  # noqa: F401  DecimalString 自定义类型

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '512bb4dc00a3'
down_revision: str | None = '144bdd18bc83'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fx_rates',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('base_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('quote_currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('rate', app.core.money.DecimalString(), nullable=False),
    sa.PrimaryKeyConstraint('date', 'base_currency', 'quote_currency')
    )
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_fx_rates_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fx_rates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fx_rates_date'))

    op.drop_table('fx_rates')
    # ### end Alembic commands ###
