"""add financials

Revision ID: 2dbf9657097c
Revises: 54acac25dd0f
Create Date: 2026-05-30 13:01:53.379289

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  SQLModel 列类型（如 AutoString）在迁移中可能用到

import app.core.money  # noqa: F401  DecimalString 自定义类型

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '2dbf9657097c'
down_revision: str | None = '54acac25dd0f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('as_of', sa.Date(), nullable=False),
    sa.Column('pe', app.core.money.DecimalString(), nullable=True),
    sa.Column('pb', app.core.money.DecimalString(), nullable=True),
    sa.Column('roe', app.core.money.DecimalString(), nullable=True),
    sa.Column('revenue_yoy', app.core.money.DecimalString(), nullable=True),
    sa.Column('profit_yoy', app.core.money.DecimalString(), nullable=True),
    sa.Column('market_cap', app.core.money.DecimalString(), nullable=True),
    sa.Column('dividend_yield', app.core.money.DecimalString(), nullable=True),
    sa.Column('eps', app.core.money.DecimalString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stock_id', 'as_of', name='uq_fin_stock_asof')
    )
    with op.batch_alter_table('financials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_financials_as_of'), ['as_of'], unique=False)
        batch_op.create_index(batch_op.f('ix_financials_stock_id'), ['stock_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('financials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_financials_stock_id'))
        batch_op.drop_index(batch_op.f('ix_financials_as_of'))

    op.drop_table('financials')
    # ### end Alembic commands ###
