"""add sync_logs

Revision ID: 144bdd18bc83
Revises: 06c630362431
Create Date: 2026-05-29 22:23:46.029083

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  SQLModel 列类型（如 AutoString）在迁移中可能用到

import app.core.money  # noqa: F401  DecimalString 自定义类型

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '144bdd18bc83'
down_revision: str | None = '06c630362431'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('market', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('symbol', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('inserted', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('skipped', sa.Integer(), nullable=False),
    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sync_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sync_logs_market'), ['market'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sync_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sync_logs_market'))
        batch_op.drop_index(batch_op.f('ix_sync_logs_created_at'))

    op.drop_table('sync_logs')
    # ### end Alembic commands ###
