"""add cash accounts and flows

Revision ID: 629afb5668ed
Revises: 512bb4dc00a3
Create Date: 2026-05-29 22:30:28.376058

"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel  # noqa: F401  SQLModel 列类型（如 AutoString）在迁移中可能用到

import app.core.money  # noqa: F401  DecimalString 自定义类型

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '629afb5668ed'
down_revision: str | None = '512bb4dc00a3'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cash_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('broker', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cash_flows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('flow_date', sa.Date(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('amount', app.core.money.DecimalString(), nullable=False),
    sa.Column('currency', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('fx_rate_to_jpy', app.core.money.DecimalString(), nullable=True),
    sa.Column('related_tx_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['cash_accounts.id'], ),
    sa.ForeignKeyConstraint(['related_tx_id'], ['transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_flows_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_flows_flow_date'), ['flow_date'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cash_flows', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_flows_flow_date'))
        batch_op.drop_index(batch_op.f('ix_cash_flows_account_id'))

    op.drop_table('cash_flows')
    op.drop_table('cash_accounts')
    # ### end Alembic commands ###
